title: Eric Chen
email: yangcheneric123@gmail.com
description: Personal projects and stuff
url: "https://bambooyc123.github.io"
baseurl: ""
repository: BambooYC123/BambooYC123.github.io
github_username: BambooYC123

permalink: /:year/:month/:day/:title/
timezone: Australia/Sydney

theme: minima

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
